name: Issue Label Commenter

on:
  issues:
    types: [labeled]

jobs:
  comment-on-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment on documentation label
        if: github.event.label.name == 'documentation'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Thank you for flagging this documentation issue. We will update it soon."
          
      - name: Comment on wontfix label
        if: github.event.label.name == 'wontfix'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "After review, we have decided not to address this issue at this time."